name: Snake Animation

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Gerar cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            profile/github-snake.gif?color_snake=#008cff&color_dots=#000000,#07111f,#003b73,#008cff,#ffffff

      - name: Salvar arquivo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/github-snake.gif
          git commit -m "Atualizar snake" || exit 0
          git push
